# Generated by Django 5.1.6 on 2025-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
    ]
