# Generated by Django 5.1.6 on 2025-07-03 11:42

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.payment_screenshot_upload_path),
        ),
    ]
